
var headerText = "Meeting Bingo";

var winText = "Winner";

var JSONBingo = {"squares": [
        {"square": "Alignment"},
        {"square": "Ask (noun)"},	
        {"square": "Ballpark"},
        {"square": "Bandwidth"},	
        {"square": "Benchmark"},	
        {"square": "Buy-in"},	
        {"square": "Capability"},	
        {"square": "Calibrate"},
        {"square": "Cutting Edge"},	   	
        {"square": "Deep dive"},
        {"square": "Deliverables"},
        {"square": "Disruptive"}    	
        {"square": "Ecosystem"},
        {"square": "Elephant in the room"},	
        {"square": "Enable"},	
        {"square": "Foundational"},
        {"square": "Framework"},
        {"square": "Granular"},	
        {"square": "Haircut"},
        {"square": "Holistic"},
        {"square": "Ideation"},	
		{"square": "Integrate"},
        {"square": "Incentivize"},
        {"square": "Infrastructure"},
		{"square": "Insights"},
        {"square": "KPI"},
        {"square": "Lever"},
        {"square": "Leverage"},	
        {"square": "Live into"},
        {"square": "Low-hanging fruit"},	
        {"square": "Mindset"},
        {"square": "Misaligned"},
        {"square": "Mission Critical"},
        {"square": "Opportunity"},	
        {"square": "Optimize"},
        {"square": "Out of the box"},	
        {"square": "Paradigm"},	
        {"square": "Productionalize"},
        {"square": "Rockstar"},	
        {"square": "Robust"},	
        {"square": "Scenario"},	
        {"square": "Streamline"},
        {"square": "Synergy"},
        {"square": "Tactical"},
        {"square": "Test and learn"},
        {"square": "Traction"},
    ]
};
