
var headerText = "Lingo Bingo";

var winTextAll = ["You are a business champion!",
                  "You are a titan of industry!"];

var winText = winTextAll[Math.floor(Math.random() * winTextAll.length)];

var JSONBingo = {"squares": [
        {"square": "Accelerate"},
        {"square": "Advancement"},
        {"square": "Agile"},
        {"square": "Align"},
        {"square": "Amplify"},
        {"square": "Analysis paralysis"},	
        {"square": "Ask (noun)"},	
        {"square": "Ballpark"},
        {"square": "Bandwidth"},	
        {"square": "Benchmark"},	
        {"square": "Best practices"},
        {"square": "Best-in-class"},
        {"square": "Buy-in"},	
        {"square": "Capability"},	
        {"square": "Calibrate"},
        {"square": "Core competency"},
        {"square": "Cross-collaborate"},
        {"square": "Cutting Edge"},	   	
        {"square": "Data-driven"},
        {"square": "Decisioning"},
        {"square": "Deep dive"},
        {"square": "Deliverable"},
        {"square": "Disrupt"},    	
        {"square": "Drill down"},
        {"square": "Ecosystem"},
        {"square": "End-to-end"},
        {"square": "First-class"},
        {"square": "Facilitate"},
        {"square": "Foundational"},
        {"square": "Framework"},
        {"square": "Future state"},
        {"square": "Granular"},	
        {"square": "Ground-up"}, 
        {"square": "Haircut"},
        {"square": "Hard stop"},
        {"square": "Higher-order thinking"},
        {"square": "Holistic"},
        {"square": "Horizontal"},
        {"square": "Ideation"},
        {"square": "Innovation"},
	    {"square": "Integrate"},
        {"square": "Incentivize"},
        {"square": "Infrastructure"},
	    {"square": "Insight"},
        {"square": "Key Player"},
        {"square": "KPI"},
        {"square": "Lever"},
        {"square": "Leverage"},	
        {"square": "Live into"},
        {"square": "Low-hanging fruit"},	
        {"square": "Mindset"},
        {"square": "Optimize"},
        {"square": "Organic"},
        {"square": "Out of the box"},	
        {"square": "Pain point"},
        {"square": "Paradigm"},	
        {"square": "Ping"},
	    {"square": "Positive intangibles"},
        {"square": "Productionalize"},
        {"square": "Push the envelope"},
        {"square": "Rockstar"},	
        {"square": "Robust"},	
        {"square": "Stakeholder"},
        {"square": "Streamline"},
        {"square": "Sustainability"},
        {"square": "Synergy"},
        {"square": "Tactical"},
        {"square": "Test and learn"},
        {"square": "Trade-off"},
        {"square": "Unpack"},
        {"square": "Wheelhouse"},
        {"square": "Win-win"}
    ]
};
